/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kevin
 */
public class Inter_ingreso_presidente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_ingreso_presidente
     */
    public Inter_ingreso_presidente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_guardar_presidente = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        boton_limpiar_presidente = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        text_field_id_presidente = new javax.swing.JTextField();
        text_field_email_presidente = new javax.swing.JTextField();
        text_field_contrasena_presidente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        text_field_nombre_presidente = new javax.swing.JTextField();
        text_field_apellido_presidente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_field_nom_user_presidente = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        combo_box_buscar_presidente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_presidente = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_field_buscar_presidente = new javax.swing.JTextField();
        boton_buscar_presidente = new javax.swing.JButton();
        boton_editar_presidente = new javax.swing.JButton();
        boton_borrar_presidente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Ingreso presidente");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_guardar_presidente.setBackground(new java.awt.Color(0, 204, 204));
        boton_guardar_presidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_guardar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        boton_guardar_presidente.setText("Guardar");
        jPanel1.add(boton_guardar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 92, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Apellido:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        boton_limpiar_presidente.setBackground(new java.awt.Color(0, 204, 0));
        boton_limpiar_presidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_limpiar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        boton_limpiar_presidente.setText("Limpiar");
        jPanel1.add(boton_limpiar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 86, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nombre usuario:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Id presidente:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Contraseña:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel1.add(text_field_id_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 193, -1));
        jPanel1.add(text_field_email_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 194, -1));
        jPanel1.add(text_field_contrasena_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 194, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Email:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        text_field_nombre_presidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_nombre_presidenteActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_nombre_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 193, -1));
        jPanel1.add(text_field_apellido_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 194, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));
        jPanel1.add(text_field_nom_user_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 194, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nombre :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        combo_box_buscar_presidente.setBackground(new java.awt.Color(255, 255, 255));
        combo_box_buscar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        combo_box_buscar_presidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo_box_buscar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 145, -1));

        table_presidente.setBackground(new java.awt.Color(255, 255, 255));
        table_presidente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_presidente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 742, 320));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("*Seleccione un registro para efectuar alguna accion de edicion o borrado* ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Buscar por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        text_field_buscar_presidente.setBackground(new java.awt.Color(255, 255, 255));
        text_field_buscar_presidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_buscar_presidenteActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_buscar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 157, -1));

        boton_buscar_presidente.setBackground(new java.awt.Color(0, 204, 204));
        boton_buscar_presidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_buscar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        boton_buscar_presidente.setText("Buscar");
        jPanel1.add(boton_buscar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, -1, -1));

        boton_editar_presidente.setBackground(new java.awt.Color(255, 255, 0));
        boton_editar_presidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_editar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        boton_editar_presidente.setText("Editar");
        jPanel1.add(boton_editar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 87, -1));

        boton_borrar_presidente.setBackground(new java.awt.Color(204, 0, 0));
        boton_borrar_presidente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_borrar_presidente.setForeground(new java.awt.Color(0, 0, 0));
        boton_borrar_presidente.setText("Borrar");
        jPanel1.add(boton_borrar_presidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 91, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 350));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 760, 470));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancha 2.0.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_field_nombre_presidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_nombre_presidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_nombre_presidenteActionPerformed

    private void text_field_buscar_presidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_buscar_presidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_buscar_presidenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar_presidente;
    private javax.swing.JButton boton_buscar_presidente;
    private javax.swing.JButton boton_editar_presidente;
    private javax.swing.JButton boton_guardar_presidente;
    private javax.swing.JButton boton_limpiar_presidente;
    private javax.swing.JComboBox<String> combo_box_buscar_presidente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_presidente;
    private javax.swing.JTextField text_field_apellido_presidente;
    private javax.swing.JTextField text_field_buscar_presidente;
    private javax.swing.JTextField text_field_contrasena_presidente;
    private javax.swing.JTextField text_field_email_presidente;
    private javax.swing.JTextField text_field_id_presidente;
    private javax.swing.JTextField text_field_nom_user_presidente;
    private javax.swing.JTextField text_field_nombre_presidente;
    // End of variables declaration//GEN-END:variables
}
