/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kevin
 */
public class Inter_ingreso_usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_ingreso_secretarias
     */
    public Inter_ingreso_usuarios() {
        initComponents();
        setearTabla();
        cargarComboFiltro();
    }

    private void setearTabla(){
        
    }
    
    private void cargarComboFiltro(){
        
    }
    
    private void guardarUsuario(){
        
    }
    
    private void eliminarUsuario(){
        
    }
    
    private void editarUsuario(){
        
    }
    
    private void limpiarTexts(){
        
    }
    
    private void filtrarTabla(){
        
    }

    private void cargarListadoUsuarios(){

    }

    private boolean filaSeleccionada(){
        return (false);
    }


    private boolean camposNoValidos(){
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        text_contrasenia = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        text_apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        text_nombre_user = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        boton_guardar_secretaria = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        boton_limpiar_secretaria = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        boton_borrar_secretaria = new javax.swing.JButton();
        combo_box_buscar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_field_buscar = new javax.swing.JTextField();
        boton_buscar_secretaria = new javax.swing.JButton();
        boton_editar_secretaria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_box_rol = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Ingreso secretaria");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Contraseña:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        text_email.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 190, -1));

        text_contrasenia.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, -1));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Email:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 30));

        text_nombre.setBackground(new java.awt.Color(255, 255, 255));
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 190, -1));

        text_apellido.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        text_nombre_user.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_nombre_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Nombre :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        boton_guardar_secretaria.setBackground(new java.awt.Color(0, 204, 204));
        boton_guardar_secretaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_guardar_secretaria.setForeground(new java.awt.Color(0, 0, 0));
        boton_guardar_secretaria.setText("Guardar");
        jPanel1.add(boton_guardar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 92, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Apellido:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        boton_limpiar_secretaria.setBackground(new java.awt.Color(0, 204, 0));
        boton_limpiar_secretaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_limpiar_secretaria.setForeground(new java.awt.Color(0, 0, 0));
        boton_limpiar_secretaria.setText("Limpiar");
        jPanel1.add(boton_limpiar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 92, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Nombre usuario:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        boton_borrar_secretaria.setBackground(new java.awt.Color(204, 0, 0));
        boton_borrar_secretaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_borrar_secretaria.setForeground(new java.awt.Color(0, 0, 0));
        boton_borrar_secretaria.setText("Borrar");
        jPanel1.add(boton_borrar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 80, -1));

        combo_box_buscar.setBackground(new java.awt.Color(255, 255, 255));
        combo_box_buscar.setForeground(new java.awt.Color(0, 0, 0));
        combo_box_buscar.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(combo_box_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 145, -1));

        table_usuarios.setBackground(new java.awt.Color(255, 255, 255));
        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(

        ));
        jScrollPane1.setViewportView(table_usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 742, 320));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("*Seleccione un registro para efectuar alguna accion de edicion o borrado* ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Buscar por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        text_field_buscar.setBackground(new java.awt.Color(255, 255, 255));
        text_field_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 157, -1));

        boton_buscar_secretaria.setBackground(new java.awt.Color(0, 204, 204));
        boton_buscar_secretaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_buscar_secretaria.setForeground(new java.awt.Color(0, 0, 0));
        boton_buscar_secretaria.setText("Buscar");
        jPanel1.add(boton_buscar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        boton_editar_secretaria.setBackground(new java.awt.Color(255, 255, 0));
        boton_editar_secretaria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_editar_secretaria.setForeground(new java.awt.Color(0, 0, 0));
        boton_editar_secretaria.setText("Editar");
        jPanel1.add(boton_editar_secretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 85, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Rol:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        combo_box_rol.setBackground(new java.awt.Color(255, 255, 255));
        combo_box_rol.setModel(new javax.swing.DefaultComboBoxModel<>());
        jPanel1.add(combo_box_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 190, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 340));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 760, 470));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancha 2.0.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Ingreso usuarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_field_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar_secretaria;
    private javax.swing.JButton boton_buscar_secretaria;
    private javax.swing.JButton boton_editar_secretaria;
    private javax.swing.JButton boton_guardar_secretaria;
    private javax.swing.JButton boton_limpiar_secretaria;
    private javax.swing.JComboBox<String> combo_box_buscar;
    private javax.swing.JComboBox<String> combo_box_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_usuarios;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_contrasenia;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_field_buscar;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_nombre_user;
    // End of variables declaration//GEN-END:variables
}
