/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kevin
 */
public class Inter_sorteo_arbitros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_sorteo_arbitros
     */
    public Inter_sorteo_arbitros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        text_box_arbitro_principal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boton_sorteo_arbitro = new javax.swing.JButton();
        text_box_lugar_partido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_calendario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_num_sorteo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Sorteo arbitros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Arbitro principal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        text_box_arbitro_principal.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(text_box_arbitro_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Sorteo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Arbitro sustituto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        boton_sorteo_arbitro.setBackground(new java.awt.Color(0, 204, 204));
        boton_sorteo_arbitro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_sorteo_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_sorteo_arbitro.setText("Generar sorteo");
        boton_sorteo_arbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sorteo_arbitroActionPerformed(evt);
            }
        });
        getContentPane().add(boton_sorteo_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 150, -1));

        text_box_lugar_partido.setBackground(new java.awt.Color(255, 255, 255));
        text_box_lugar_partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_box_lugar_partidoActionPerformed(evt);
            }
        });
        getContentPane().add(text_box_lugar_partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 159, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Listado de arbitros a sortear");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        table_calendario.setBackground(new java.awt.Color(255, 255, 255));
        table_calendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
            }
        ));
        jScrollPane1.setViewportView(table_calendario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 640, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de numeros a sortear");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jTextField1_num_sorteo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1_num_sorteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 80, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel13.setText("jLabel5");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 280));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel14.setText("jLabel5");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 660, 410));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancha 2.0.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_sorteo_arbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sorteo_arbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_sorteo_arbitroActionPerformed

    private void text_box_lugar_partidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_box_lugar_partidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_box_lugar_partidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_sorteo_arbitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1_num_sorteo;
    private javax.swing.JTable table_calendario;
    private javax.swing.JFormattedTextField text_box_arbitro_principal;
    private javax.swing.JTextField text_box_lugar_partido;
    // End of variables declaration//GEN-END:variables
}
