/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author kevin
 */
public class Inter_edicion_arbitro extends javax.swing.JInternalFrame {

    
    //Variable de fondo
    FondoPanel fondo= new FondoPanel();
    
    
    public Inter_edicion_arbitro() {
        
        this.setContentPane(fondo);//Aqui establecimos la imagen de fondo al Jframe
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_limpiar_arbitro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_field_altura_arbitro = new javax.swing.JTextField();
        text_field_id_arbitro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_field_edad_arbitro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_field_nombre_arbitro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_field_email_arbtiro = new javax.swing.JTextField();
        combo_box_categoria_arbitro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_field_contrasena_arbitro = new javax.swing.JTextField();
        text_field_partidos_arbitro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boton_guardar_arbitro = new javax.swing.JButton();
        text_field_dorsal_arbitro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        text_field_buscar_arbitro = new javax.swing.JTextField();
        boton_buscar_arbitro = new javax.swing.JButton();
        boton_editar_arbitro = new javax.swing.JButton();
        boton_borrar_arbitro = new javax.swing.JButton();
        combo_box_buscar_arbitro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_arbitro = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ingreso arbitro");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_limpiar_arbitro.setBackground(new java.awt.Color(0, 204, 0));
        boton_limpiar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_limpiar_arbitro.setText("Limpiar");
        jPanel1.add(boton_limpiar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 97, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Partidos:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Id arbitro:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        text_field_altura_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_altura_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 194, -1));

        text_field_id_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_id_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 192, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Dorsal:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        text_field_edad_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_edad_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 194, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Altura:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo electronico:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        text_field_nombre_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        text_field_nombre_arbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_nombre_arbitroActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_nombre_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 192, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        text_field_email_arbtiro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_email_arbtiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 194, -1));

        combo_box_categoria_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        combo_box_categoria_arbitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo_box_categoria_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 194, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingreso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        text_field_contrasena_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_contrasena_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 194, -1));

        text_field_partidos_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_partidos_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 194, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Categoria:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        boton_guardar_arbitro.setBackground(new java.awt.Color(0, 204, 204));
        boton_guardar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_guardar_arbitro.setText("Guardar");
        jPanel1.add(boton_guardar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 92, -1));

        text_field_dorsal_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_dorsal_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 194, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("*Seleccione un registro para efectuar alguna accion de edicion o borrado* ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel11.setText("Buscar por:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        text_field_buscar_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        text_field_buscar_arbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_buscar_arbitroActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_buscar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 157, -1));

        boton_buscar_arbitro.setBackground(new java.awt.Color(0, 204, 204));
        boton_buscar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_buscar_arbitro.setText("Buscar");
        jPanel1.add(boton_buscar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        boton_editar_arbitro.setBackground(new java.awt.Color(255, 255, 0));
        boton_editar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_editar_arbitro.setText("Editar");
        jPanel1.add(boton_editar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 94, -1));

        boton_borrar_arbitro.setBackground(new java.awt.Color(204, 0, 0));
        boton_borrar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_borrar_arbitro.setText("Borrar");
        jPanel1.add(boton_borrar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 92, -1));

        combo_box_buscar_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        combo_box_buscar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        combo_box_buscar_arbitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combo_box_buscar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 145, -1));

        table_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        table_arbitro.setForeground(new java.awt.Color(51, 51, 51));
        table_arbitro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_arbitro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 742, 320));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel13.setText("jLabel5");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 350, 460));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo blanco.jpg"))); // NOI18N
        jLabel14.setText("jLabel5");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 760, 460));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancha 2.0.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_field_nombre_arbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_nombre_arbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_nombre_arbitroActionPerformed

    private void text_field_buscar_arbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_buscar_arbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_buscar_arbitroActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar_arbitro;
    private javax.swing.JButton boton_buscar_arbitro;
    private javax.swing.JButton boton_editar_arbitro;
    private javax.swing.JButton boton_guardar_arbitro;
    private javax.swing.JButton boton_limpiar_arbitro;
    private javax.swing.JComboBox<String> combo_box_buscar_arbitro;
    private javax.swing.JComboBox<String> combo_box_categoria_arbitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_arbitro;
    private javax.swing.JTextField text_field_altura_arbitro;
    private javax.swing.JTextField text_field_buscar_arbitro;
    private javax.swing.JTextField text_field_contrasena_arbitro;
    private javax.swing.JTextField text_field_dorsal_arbitro;
    private javax.swing.JTextField text_field_edad_arbitro;
    private javax.swing.JTextField text_field_email_arbtiro;
    private javax.swing.JTextField text_field_id_arbitro;
    private javax.swing.JTextField text_field_nombre_arbitro;
    private javax.swing.JTextField text_field_partidos_arbitro;
    // End of variables declaration//GEN-END:variables

    //Clase interna para poder agregar un fondo de imagen
    class FondoPanel extends JPanel{
        
        //Variable
        private Image imagen;
        
        
        //Sobreescritura del metodo Paint
        @Override
        public void paint(Graphics g){
            
            imagen = new ImageIcon(getClass().getResource("/imagenes/cesped_cancha_futbol.jpg")).getImage();
            
            //Dibujamos la imagen
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            
            //Metodo set
            setOpaque(false);
            
            //Llamada al metodo de pintado
            super.paint(g);
        }
        
    }

}



