
package vista;

import controlador.Controlador_actas_partido;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Actas_partido;


public class Inter_ingreso_actas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingreso_actas
     */
    public Inter_ingreso_actas() {
        initComponents();
        
        this.setSize(new Dimension(727, 399));//Permite crear la dimension de la pantalla
        this.setTitle("ÁRBITRO: INGRESO NUEVA ACTA DE PARTIDO");
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Boton_ingresar_nueva_acta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_text_box = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hora_inicio_text_box = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hora_fin_text_box = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        equipo_rival_text_box = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        equipo_local_text_box = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        duracion_partido_text_box = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        goles_rival_text_box = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        goles_local_text_box = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        equipo_ganador_text_box = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        id_arbitro_text_box = new javax.swing.JTextField();
        jbtActualizar2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir_acta.png"))); // NOI18N
        jLabel1.setText("Nueva acta");

        Boton_ingresar_nueva_acta.setBackground(new java.awt.Color(0, 153, 255));
        Boton_ingresar_nueva_acta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boton_ingresar_nueva_acta.setForeground(new java.awt.Color(255, 255, 255));
        Boton_ingresar_nueva_acta.setText("Ingresar acta");
        Boton_ingresar_nueva_acta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ingresar_nueva_actaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Id del acta:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hora inicio partido:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Hora fin partido:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Equipo rival:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Equipo local:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(equipo_local_text_box, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(equipo_rival_text_box)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hora_fin_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hora_inicio_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hora_inicio_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hora_fin_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(equipo_rival_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(equipo_local_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Duracion partido:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Goles equipo rival:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Goles equipo local:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Equipo ganador:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Id arbitro:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(26, 26, 26))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(25, 25, 25)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(40, 40, 40)))
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duracion_partido_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goles_rival_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goles_local_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipo_ganador_text_box)
                    .addComponent(id_arbitro_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(duracion_partido_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(goles_rival_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(goles_local_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(equipo_ganador_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(id_arbitro_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jbtActualizar2.setBackground(new java.awt.Color(51, 255, 51));
        jbtActualizar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtActualizar2.setText("Actualizar");
        jbtActualizar2.setEnabled(false);
        jbtActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(Boton_ingresar_nueva_acta)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtActualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_ingresar_nueva_acta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtActualizar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ingresar_nueva_actaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ingresar_nueva_actaActionPerformed
        
        this.ingreso_acta();//Llamada de metodo
    }//GEN-LAST:event_Boton_ingresar_nueva_actaActionPerformed

    private void jbtActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizar2ActionPerformed
        Controlador_actas_partido controller = new Controlador_actas_partido();
        
        Actas_partido acta = new Actas_partido();
        acta.setId_acta_partido(Integer.parseInt(id_text_box.getText()));
        acta.setDuracion_partido(Integer.parseInt(duracion_partido_text_box.getText()));
        acta.setHora_inicio_partido(hora_inicio_text_box.getText());
        acta.setHora_fin_partido(hora_fin_text_box.getText());
        acta.setNombre_equipo_local(equipo_local_text_box.getText());
        acta.setNombre_equipo_rival(equipo_rival_text_box.getText());
        acta.setEquipo_ganador(equipo_ganador_text_box.getText());
        acta.setGoles_equipo_rival(Integer.parseInt(goles_rival_text_box.getText()));
        acta.setGoles_equipo_local(Integer.parseInt(goles_local_text_box.getText()));
        //acta.setId_arbitro(Integer.parseInt(id_arbitro_text_box.getText()));
        
        
         String mensaje = controller.actualizarActa(acta);
         JOptionPane.showMessageDialog(null, mensaje, "PopUp Dialog", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtActualizar2ActionPerformed

    
    //Metodo para dar funcionalidad al boton ingreso de acta
    private void ingreso_acta(){
        
        Actas_partido acta_partido= new Actas_partido();//Instancia de tipo Actas_partido
        
        Controlador_actas_partido controlador_acta_partido= new Controlador_actas_partido();
        
        
        
        //Condicion para validar si los campos estan vacios
        if(id_text_box.getText().isEmpty() || hora_inicio_text_box.getText().isEmpty()
            || hora_fin_text_box.getText().isEmpty() || equipo_rival_text_box.getText().isEmpty()
            || equipo_local_text_box.getText().isEmpty() || duracion_partido_text_box.getText().isEmpty()
            || goles_rival_text_box.getText().isEmpty() || goles_local_text_box.getText().isEmpty()
            || equipo_ganador_text_box.getText().isEmpty() || id_arbitro_text_box.getText().isEmpty()){
            
            
            JOptionPane.showMessageDialog(null, "Primero llena todos los campos PAPÁ!!!");

            
        }else{
            
            //Esto me permite capturar lo que hay en las cajas de texto y guardar en los 
            //atributos de clase de actas_partido
            acta_partido.setId_acta_partido(Integer.parseInt(id_text_box.getText()));
            acta_partido.setHora_inicio_partido(hora_inicio_text_box.getText());
            acta_partido.setHora_fin_partido(hora_fin_text_box.getText());
            acta_partido.setNombre_equipo_rival(equipo_rival_text_box.getText().trim());
            acta_partido.setNombre_equipo_local(equipo_local_text_box.getText().trim());
            acta_partido.setDuracion_partido(Integer.parseInt(duracion_partido_text_box.getText()));
            acta_partido.setGoles_equipo_rival(Integer.parseInt(goles_rival_text_box.getText()));
            acta_partido.setGoles_equipo_local(Integer.parseInt(goles_local_text_box.getText()));
            acta_partido.setEquipo_ganador(equipo_ganador_text_box.getText().trim());
            //acta_partido.setId_arbitro(Integer.parseInt(id_arbitro_text_box.getText()));
            
            
            //Condicion que me indica si guardaron los cambios
            if(controlador_acta_partido.guardar(acta_partido)){
                
                JOptionPane.showMessageDialog(null, "Registro exitoso");
            }else{
                
                JOptionPane.showMessageDialog(null, "Error de guardado, intentelo otra vez");
            }
        }
        
        //Limpieza de campos
            id_text_box.setText("");
            hora_inicio_text_box.setText("");
            hora_fin_text_box.setText("");
            equipo_rival_text_box.setText("");
            equipo_local_text_box.setText("");
            duracion_partido_text_box.setText("");
            goles_rival_text_box.setText("");
            goles_local_text_box.setText("");
            equipo_ganador_text_box.setText("");
            id_arbitro_text_box.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_ingresar_nueva_acta;
    public javax.swing.JTextField duracion_partido_text_box;
    public javax.swing.JTextField equipo_ganador_text_box;
    public javax.swing.JTextField equipo_local_text_box;
    public javax.swing.JTextField equipo_rival_text_box;
    public javax.swing.JTextField goles_local_text_box;
    public javax.swing.JTextField goles_rival_text_box;
    public javax.swing.JTextField hora_fin_text_box;
    public javax.swing.JTextField hora_inicio_text_box;
    public javax.swing.JTextField id_arbitro_text_box;
    public javax.swing.JTextField id_text_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton jbtActualizar2;
    // End of variables declaration//GEN-END:variables
}
