
package vista;

import controlador.Controlador_actas_partido;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Actas_partido;


public class Inter_ingreso_actas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ingreso_actas
     */
    public Inter_ingreso_actas() {
        initComponents();
        
        this.setSize(new Dimension(550, 630));//Permite crear la dimension de la pantalla
        this.setTitle("Nueva acta de partido");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id_text_box = new javax.swing.JTextField();
        hora_inicio_text_box = new javax.swing.JTextField();
        hora_fin_text_box = new javax.swing.JTextField();
        equipo_rival_text_box = new javax.swing.JTextField();
        equipo_local_text_box = new javax.swing.JTextField();
        duracion_partido_text_box = new javax.swing.JTextField();
        goles_rival_text_box = new javax.swing.JTextField();
        goles_local_text_box = new javax.swing.JTextField();
        equipo_ganador_text_box = new javax.swing.JTextField();
        id_arbitro_text_box = new javax.swing.JTextField();
        Boton_ingresar_nueva_acta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nueva acta");

        jLabel2.setText("Id del acta:");

        jLabel3.setText("Hora inicio partido:");

        jLabel4.setText("Hora fin partido:");

        jLabel5.setText("Equipo rival:");

        jLabel6.setText("Equipo local:");

        jLabel7.setText("Duracion partido:");

        jLabel8.setText("Goles equipo rival:");

        jLabel9.setText("Goles equipo local:");

        jLabel10.setText("Equipo ganador:");

        jLabel11.setText("Id arbitro:");

        Boton_ingresar_nueva_acta.setText("Ingresar acta");
        Boton_ingresar_nueva_acta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ingresar_nueva_actaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(id_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hora_inicio_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(goles_local_text_box)
                                    .addComponent(equipo_ganador_text_box)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(74, 74, 74)
                                .addComponent(id_arbitro_text_box))
                            .addComponent(hora_fin_text_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo_rival_text_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipo_local_text_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duracion_partido_text_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goles_rival_text_box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_ingresar_nueva_acta)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hora_inicio_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hora_fin_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(equipo_rival_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(equipo_local_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(duracion_partido_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(goles_rival_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(goles_local_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(equipo_ganador_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id_arbitro_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Boton_ingresar_nueva_acta)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ingresar_nueva_actaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ingresar_nueva_actaActionPerformed
        
        this.ingreso_acta();//Llamada de metodo
    }//GEN-LAST:event_Boton_ingresar_nueva_actaActionPerformed

    
    //Metodo para dar funcionalidad al boton ingreso de acta
    private void ingreso_acta(){
        
        Actas_partido acta_partido= new Actas_partido();//Instancia de tipo Actas_partido
        
        Controlador_actas_partido controlador_acta_partido= new Controlador_actas_partido();
        
        
        
        //Condicion para validar si los campos estan vacios
        if(id_text_box.getText().isEmpty() || hora_inicio_text_box.getText().isEmpty()
            || hora_fin_text_box.getText().isEmpty() || equipo_rival_text_box.getText().isEmpty()
            || equipo_local_text_box.getText().isEmpty() || duracion_partido_text_box.getText().isEmpty()
            || goles_rival_text_box.getText().isEmpty() || goles_local_text_box.getText().isEmpty()
            || equipo_ganador_text_box.getText().isEmpty() || id_arbitro_text_box.getText().isEmpty()){
            
            
            JOptionPane.showMessageDialog(null, "Primero llena todos los campos PAPÁ!!!");

            
        }else{
            
            //Esto me permite capturar lo que hay en las cajas de texto y guardar en los 
            //atributos de clase de actas_partido
            acta_partido.setId_acta_partido(Integer.parseInt(id_text_box.getText()));
            acta_partido.setHora_inicio_partido(hora_inicio_text_box.getText());
            acta_partido.setHora_fin_partido(hora_fin_text_box.getText());
            acta_partido.setNombre_equipo_rival(equipo_rival_text_box.getText().trim());
            acta_partido.setNombre_equipo_local(equipo_local_text_box.getText().trim());
            acta_partido.setDuracion_partido(Integer.parseInt(duracion_partido_text_box.getText()));
            acta_partido.setGoles_equipo_rival(Integer.parseInt(goles_rival_text_box.getText()));
            acta_partido.setGoles_equipo_local(Integer.parseInt(goles_local_text_box.getText()));
            acta_partido.setEquipo_ganador(equipo_ganador_text_box.getText().trim());
            acta_partido.setId_arbitro(Integer.parseInt(id_arbitro_text_box.getText()));
            
            
            //Condicion que me indica si guardaron los cambios
            if(controlador_acta_partido.guardar(acta_partido)){
                
                JOptionPane.showMessageDialog(null, "Registro exitoso");
            }else{
                
                JOptionPane.showMessageDialog(null, "Error de guardado, intentelo otra vez");
            }
        }
        
        //Limpieza de campos
            id_text_box.setText("");
            hora_inicio_text_box.setText("");
            hora_fin_text_box.setText("");
            equipo_rival_text_box.setText("");
            equipo_local_text_box.setText("");
            duracion_partido_text_box.setText("");
            goles_rival_text_box.setText("");
            goles_local_text_box.setText("");
            equipo_ganador_text_box.setText("");
            id_arbitro_text_box.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_ingresar_nueva_acta;
    private javax.swing.JTextField duracion_partido_text_box;
    private javax.swing.JTextField equipo_ganador_text_box;
    private javax.swing.JTextField equipo_local_text_box;
    private javax.swing.JTextField equipo_rival_text_box;
    private javax.swing.JTextField goles_local_text_box;
    private javax.swing.JTextField goles_rival_text_box;
    private javax.swing.JTextField hora_fin_text_box;
    private javax.swing.JTextField hora_inicio_text_box;
    private javax.swing.JTextField id_arbitro_text_box;
    private javax.swing.JTextField id_text_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
