/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kevin
 */
public class Inter_consulta_asistencia_arbitros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inter_consulta_asistencia_arbitros
     */
    public Inter_consulta_asistencia_arbitros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_asistencia_arbitro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        text_field_buscar_arbitro = new javax.swing.JTextField();
        boton_buscar_arbitro = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Asistencia arbitros");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_asistencia_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        table_asistencia_arbitro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_asistencia_arbitro);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, 740, 293));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del arbitro a buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 34, -1, -1));

        text_field_buscar_arbitro.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(text_field_buscar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 31, 220, -1));

        boton_buscar_arbitro.setBackground(new java.awt.Color(0, 204, 204));
        boton_buscar_arbitro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_buscar_arbitro.setForeground(new java.awt.Color(0, 0, 0));
        boton_buscar_arbitro.setText("Buscar");
        jPanel1.add(boton_buscar_arbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 31, 81, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancha 2.0.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 810, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar_arbitro;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_asistencia_arbitro;
    private javax.swing.JTextField text_field_buscar_arbitro;
    // End of variables declaration//GEN-END:variables
}
