
package vista;

import javax.swing.JDesktopPane;



public class Ventana_arbitro extends javax.swing.JFrame {

    
    //Me permitira usar el panel principal de la ventana para mostrar otras ventanas
    //emergentes del menu.
    public static JDesktopPane panel_principal_arbitro;
    
    
    /**
     * Creates new form Arbitro
     */
    public Ventana_arbitro() {
        initComponents();
        this.setLocationRelativeTo(null);//centra la ventana
        this.setTitle("MENÚ ÁRBITRO - SISTEMA DE GESTIÓN DE ARBITROS");//Me [ermite modificar el titulo de la ventana
        
        this.setExtendedState(this.MAXIMIZED_BOTH);//Me muestra la ventana en pantalla completa desde el inicio del programa
        
        this.setLayout(null);
        
        //Intancia de tipo JDesktopPane
        panel_principal_arbitro= new JDesktopPane();
        
        int ancho= java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;//Se usa para el alto del panel
        int alto= java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;//Se usa para el ancho del panel
        
        
        //Es para indicar al panel donde empieza y donde termina
        //El -110 es el tamano de la barra de tareas.
        this.panel_principal_arbitro.setBounds(0, 0, ancho,(alto-110));
        
        this.add(panel_principal_arbitro);//Anado el JDesktopPane al panel principal.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        actas_partido_menu = new javax.swing.JMenu();
        ingreso_acta_opcion = new javax.swing.JMenuItem();
        consulta_acta_opcion = new javax.swing.JMenuItem();
        actualizar_acta_opcion = new javax.swing.JMenuItem();
        hora_asistencia_menu = new javax.swing.JMenu();
        ingreso_hora_opcion = new javax.swing.JMenuItem();
        cerrar_sesion_menu = new javax.swing.JMenu();
        salir_opcion = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actas_partido_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acta.png"))); // NOI18N
        actas_partido_menu.setText("Actas de partido");
        actas_partido_menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actas_partido_menu.setPreferredSize(new java.awt.Dimension(180, 30));

        ingreso_acta_opcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingreso_acta_opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir_acta.png"))); // NOI18N
        ingreso_acta_opcion.setText("Ingreso");
        ingreso_acta_opcion.setPreferredSize(new java.awt.Dimension(180, 35));
        ingreso_acta_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso_acta_opcionActionPerformed(evt);
            }
        });
        actas_partido_menu.add(ingreso_acta_opcion);

        consulta_acta_opcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consulta_acta_opcion.setText("Consulta");
        consulta_acta_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_acta_opcionActionPerformed(evt);
            }
        });
        actas_partido_menu.add(consulta_acta_opcion);

        actualizar_acta_opcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualizar_acta_opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar_acta.png"))); // NOI18N
        actualizar_acta_opcion.setText("Actualizar");
        actualizar_acta_opcion.setPreferredSize(new java.awt.Dimension(180, 35));
        actualizar_acta_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_acta_opcionActionPerformed(evt);
            }
        });
        actas_partido_menu.add(actualizar_acta_opcion);

        jMenuBar1.add(actas_partido_menu);

        hora_asistencia_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hora.png"))); // NOI18N
        hora_asistencia_menu.setText("Hora de asistencia");
        hora_asistencia_menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hora_asistencia_menu.setPreferredSize(new java.awt.Dimension(180, 30));

        ingreso_hora_opcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ingreso_hora_opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar_hora.png"))); // NOI18N
        ingreso_hora_opcion.setText("Ingresar");
        ingreso_hora_opcion.setPreferredSize(new java.awt.Dimension(180, 35));
        hora_asistencia_menu.add(ingreso_hora_opcion);

        jMenuBar1.add(hora_asistencia_menu);

        cerrar_sesion_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        cerrar_sesion_menu.setText("Cerrar sesión");
        cerrar_sesion_menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrar_sesion_menu.setPreferredSize(new java.awt.Dimension(180, 30));

        salir_opcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir_opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        salir_opcion.setText("Salir");
        salir_opcion.setPreferredSize(new java.awt.Dimension(180, 35));
        salir_opcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_opcionActionPerformed(evt);
            }
        });
        cerrar_sesion_menu.add(salir_opcion);

        jMenuBar1.add(cerrar_sesion_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingreso_acta_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso_acta_opcionActionPerformed
        
        //Instanciacion
        Inter_ingreso_actas categoria= new Inter_ingreso_actas();
        
        panel_principal_arbitro.add(categoria);//Pasamos el objeto categoria al panel arbitro
        
        categoria.setVisible(true);//Me sirve para mostrar la ventana categoria
           
    }//GEN-LAST:event_ingreso_acta_opcionActionPerformed

    private void actualizar_acta_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_acta_opcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizar_acta_opcionActionPerformed

    //Opcion salir del menu desplegable cerrar sesion
    private void salir_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_opcionActionPerformed
        
        this.cerrar_sesion();//Llamada del metodo salir
    }//GEN-LAST:event_salir_opcionActionPerformed

    private void consulta_acta_opcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_acta_opcionActionPerformed
        
        
        //Instancia
        Internal_consulta_actas consulta_actas= new Internal_consulta_actas();
        
        panel_principal_arbitro.add(consulta_actas);//Se agrega la ventana interna de consulta actas
                                                    //al panel principal.
        
        consulta_actas.setVisible(true);//Sirve para hacer visible la pantalla
        
        
        
    }//GEN-LAST:event_consulta_acta_opcionActionPerformed

    
    
    private void cerrar_sesion(){
        
        this.dispose();//Metodo para cerrar ejecucion de ventana actual
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_arbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_arbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_arbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_arbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_arbitro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actas_partido_menu;
    private javax.swing.JMenuItem actualizar_acta_opcion;
    private javax.swing.JMenu cerrar_sesion_menu;
    private javax.swing.JMenuItem consulta_acta_opcion;
    private javax.swing.JMenu hora_asistencia_menu;
    private javax.swing.JMenuItem ingreso_acta_opcion;
    private javax.swing.JMenuItem ingreso_hora_opcion;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem salir_opcion;
    // End of variables declaration//GEN-END:variables
}
